# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: '*** Build Http Projects ***'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'CodeLifter.Http/CodeLifter.Http.csproj'

- task: DotNetCoreCLI@2
  displayName: '*** Build Demo Projects ***'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'CodeLifter.Http.Demo/CodeLifter.Http.Demo.csproj'
    
- task: DotNetCoreCLI@2
  displayName: '*** Test CodeLifter.Http ***'
  inputs:
    command: test
    projects: 'CodeLifter.Http.Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'CodeLifter.Http/CodeLifter.Http.csproj'
    nobuild: false
    majorVersion: '1'
    minorVersion: '5'
    patchVersion: '1'
